SCOPE = "https://www.googleapis.com/auth/spreadsheets"
SPREADSHEET_ID = "19VJipmPrzogeVWDyIKLrtsk_CXu6ts4FdZV-7aeAThg"
SHEET_NAME = "Database"
GSHEET_URL = f"https://docs.google.com/spreadsheets/d/{SPREADSHEET_ID}"
COMMENT_TEMPLATE_MD = """{} - {} > {}"""